# Generated by Django 3.0 on 2025-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaycareApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='place',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Email',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='First_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
