# Generated by Django 3.0 on 2025-03-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaycareApp', '0002_auto_20250327_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
