# Generated by Django 3.0 on 2025-03-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DaycareApp', '0003_fee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='student',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DaycareApp.parent'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
