# Generated by Django 3.0 on 2025-03-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DaycareApp', '0004_auto_20250328_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DaycareApp.staff'),
        ),
    ]
