# Generated by Django 3.2.25 on 2025-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaycareApp', '0005_enquiry_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
