# Generated by Django 4.0 on 2025-04-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaycareApp', '0006_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
